# version: "20"

# services:
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     ports:
#       - 8000:8000

version: "3.8"

services:
  api:
    build: ./productCatalogue
    container_name: product_curd_api
    ports:
      - "8000:8000"

  frontend:
    build: ./product-catalouge-app-frontend
    container_name: product_curd_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./product-catalouge-app-frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
